---
stages:
  - lint
  - publish

lint:
  stage: lint
  image: registry.gitlab.com/pipeline-components/ansible-lint:latest
  script:
    - ansible-lint --show-relpath .

publish:
  stage: publish
  image: registry.gitlab.com/asharas/ansible-docker:latest
  script:
    - ansible-galaxy role import --role-name eco_server --api-key $GALAXY_API_KEY Asharas Eco-Server
  only:
    - main
    - CI
