---
- name: Create conf dir if it doesn't exist
  ansible.builtin.file:
    path: "{{ eco_rootdir }}/Configs"
    state: directory
    owner: "{{ eco_user }}"
    group: "{{ eco_group }}"
    mode: 0755

- name: Create Pause conf if it doesn't exist
  ansible.builtin.template:
    src: "Pause.eco.j2"
    dest: "{{ eco_rootdir }}/Configs/Pause.eco"
    owner: "{{ eco_user }}"
    group: "{{ eco_group }}"
    mode: 0644
    force: false

- name: Generate Network config
  include_tasks: config_network.yml

- name: Template Maintenance config
  ansible.builtin.template:
    src: "Maintenance.eco.j2"
    dest: "{{ eco_rootdir }}/Configs/Maintenance.eco"
    owner: "{{ eco_user }}"
    group: "{{ eco_group }}"
    mode: 0644
    force: false
  when: eco_autoshutdown_hour != -1

- name: Generate config
  include_tasks: config_subtask.yml
  loop: "{{ eco_generate_conf }}"
  when: not ansible_check_mode
