---
- name: Create conf dir if it doesn't exist
  file:
    path: "{{ eco_rootdir }}/Configs"
    state: directory
    owner: "{{ eco_user }}"
    group: "{{ eco_group }}"
    mode: '0755'

- name: Check if Pause conf exists
  stat:
    path: "{{ eco_rootdir }}/Configs/Pause.eco"
  register: pause_conf

- name: Create Pause conf if it doesn't exist
  template:
    src: "Pause.eco.j2"
    dest: "{{ eco_rootdir }}/Configs/Pause.eco"
    owner: "{{ eco_user }}"
    group: "{{ eco_group }}"
    mode: '0644'
  when: not pause_conf.stat.exists

- name: Generate config
  include_tasks: config_subtask.yml
  loop: "{{ eco_generate_conf }}"
