---
- name: Install required packages
  ansible.builtin.apt:
    name: iptables
    state: present

- name: Accept Established and Related connexions
  ansible.builtin.iptables:
    state: present
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Accept all traffic on loopback
  ansible.builtin.iptables:
    state: present
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: Allow SSH
  ansible.builtin.iptables:
    state: present
    chain: INPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT

- name: Nginx iptables HTTP rule
  ansible.builtin.iptables:
    state: present
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
  when: eco_rp is defined and (eco_rp | bool) or
        eco_rp_tls is defined and (eco_rp_tls | bool)

- name: Nginx iptables HTTPS rule
  ansible.builtin.iptables:
    state: present
    chain: INPUT
    protocol: tcp
    destination_port: 443
    jump: ACCEPT
  when: eco_rp_tls is defined and (eco_rp_tls | bool)

- name: Eco web iptables rule
  ansible.builtin.iptables:
    state: present
    chain: INPUT
    protocol: tcp
    destination_port: "{{ eco_web_port }}"
    jump: ACCEPT
  when:
    - eco_rp is undefined or not (eco_rp | bool)
    - eco_rp_tls is undefined or not (eco_rp_tls | bool)

- name: Eco gameserver iptables rules
  ansible.builtin.iptables:
    state: present
    chain: INPUT
    protocol: "{{ item }}"
    destination_ports: "{{ eco_game_port }}"
    jump: ACCEPT
  loop:
    - tcp
    - udp

- name: Set INPUT and FORWARD chain policy
  ansible.builtin.iptables:
    state: present
    chain: "{{ item }}"
    policy: DROP
  loop:
    - INPUT
    - FORWARD
