---
- name: Install required packages
  apt:
    name: iptables
    state: present

- name: Accept Established and Related connexions
  iptables:
    state: present
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Accept all traffic on loopback
  iptables:
    state: present
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: Allow SSH
  iptables:
    state: present
    chain: INPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT

- name: Nginx iptables rules
  iptables:
    state: present
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
  loop:
    - 80
    - 443
  when: eco_revproxy is defined and (eco_revproxy | bool)

- name: Eco web iptables rule
  iptables:
    state: present
    chain: INPUT
    protocol: tcp
    destination_port: "{{ eco_web_port }}"
    jump: ACCEPT
  when: eco_revproxy is undefined or not (eco_revproxy | bool)

- name: Eco gameserver iptables rules
  iptables:
    state: present
    chain: INPUT
    protocol: "{{ item }}"
    destination_ports: "{{ eco_game_port }}"
    jump: ACCEPT
  loop:
    - tcp
    - udp

- name: Set INPUT and FORWARD chain policy
  iptables:
    state: present
    chain: "{{ item }}"
    policy: DROP
  loop:
    - INPUT
    - FORWARD
