---
- import_tasks: install.yml

- import_tasks: service.yml
  notify: Restart Eco

- import_tasks: config.yml
  notify: Restart Eco

- import_tasks: mods.yml
  notify: Restart Eco

- import_tasks: iptables.yml
  when: eco_iptables is defined and (eco_iptables | bool)

- import_tasks: revproxy.yml
  when: eco_revproxy is defined and (eco_revproxy | bool)
  notify: Reload Nginx
