---
- name: Install required packages
  apt:
    name: unzip
    state: present

- import_tasks: mods_discordlink.yml
  when: eco_dislink_enable

- import_tasks: mods_costcalc.yml
  when: eco_costcalc_enable | bool
