---
- name: Install required packages
  apt:
    name: unzip
    state: present

- import_tasks: mods_discordlink.yml
  when: eco_dislink_enable is defined and (eco_dislink_enable | bool)

- import_tasks: mods_costcalc.yml
  when: eco_costcalc_enable is defined and (eco_costcalc_enable | bool)
