---
- name: Download Cost Calculator {{ eco_costcalc_version }}
  get_url:
    url: "{{ eco_costcalc_dl_url }}"
    dest: "/tmp/{{ eco_costcalc_archive_name }}"
  changed_when: false

- name: Unzip Cost Calculator
  unarchive:
    src: "/tmp/{{ eco_costcalc_archive_name }}"
    remote_src: yes
    dest: "/tmp/"
    owner: "{{ eco_user }}"
    group: "{{ eco_group }}"
  changed_when: false

- name: Copy mod dll to Mods dir
  copy:
    src: "/tmp/CostCalculator/CostCalculator.dll"
    remote_src: yes
    dest: "{{ eco_rootdir }}/Mods/"
    owner: "{{ eco_user }}"
    group: "{{ eco_group }}"
    mode: 0640

- name: Remove Cost Calculator archive
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/{{ eco_costcalc_archive_name }}"
    - "/tmp/CostCalculator/"
  changed_when: false
