---
- name: Ensure pip3 in installed
  package:
    name: python3-pip
    state: present

- name: Install pyOpenssl library
  pip:
    name: pyopenssl
    state: present

- name: Create certificate directory
  file:
    path: "{{ eco_revproxy_tls_crt | dirname }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Generate TLS key
  openssl_privatekey:
    path: "{{ eco_revproxy_tls_key }}"
    state: present
    owner: root
    group: root

- name: Generate CSR
  openssl_csr:
    path: "{{ eco_revproxy_tls_csr }}"
    privatekey_path: "{{ eco_revproxy_tls_key }}"
    common_name:
      - "{{ eco_remote_address }}"

- name: Generate TLS self-signed certificate
  openssl_certificate:
    provider: selfsigned
    csr_path: "{{ eco_revproxy_tls_csr }}"
    privatekey_path: "{{ eco_revproxy_tls_key }}"
    path: "{{ eco_revproxy_tls_crt }}"
    state: present
    selfsigned_not_after: +365d
  ignore_errors: "{{ ansible_check_mode }}"
