---
- name: Generate self-signed certificate
  include_tasks: revproxy_tls_selfsigned.yml
  when: eco_rp_tls_selfsigned

- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Template nginx conf for Eco
  ansible.builtin.template:
    src: nginx.eco.conf.j2
    dest: /etc/nginx/sites-available/eco.conf
    mode: 0644
    lstrip_blocks: true

- name: Disable the default site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Enable Eco conf
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/eco.conf
    src: /etc/nginx/sites-available/eco.conf
    state: link
    owner: root
    group: root
  ignore_errors: "{{ ansible_check_mode }}"
