---
- name: Create eco.service file
  template:
    src: eco.service.j2
    dest: /lib/systemd/system/eco.service
    mode: 0644

- name: Enable eco.service and reload daemon
  systemd:
    name: eco.service
    enabled: yes
    daemon-reload: yes
  # timeout: 300
