---
- name: Create eco.service file
  ansible.builtin.template:
    src: eco.service.j2
    dest: /lib/systemd/system/eco.service
    mode: 0644

- name: Enable eco.service and reload daemon
  ansible.builtin.systemd:
    name: eco.service
    enabled: true
    daemon-reload: true
  # timeout: 300
