# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	# General Vagrant VM configuration.
	config.vm.box = "debian/bullseye64"
	config.ssh.insert_key = true
	config.vm.synced_folder ".", "/vagrant", disabled: true
	config.vm.provider :virtualbox do |v|
		v.memory = 4096
		v.cpus = 2
		v.linked_clone = true
	end

	config.vm.define "eco" do |app|
		app.vm.hostname = "eco.localhost"
		app.vm.network :private_network, ip: "192.168.56.31"
  end

		# Add $HOME/.ssh/id.pub to root and vagrant users

		vagrant_root = File.dirname(__FILE__)
		ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id.pub").first.strip
	  config.vm.provision 'shell', inline: 'mkdir -p /root/.ssh'
	  config.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /root/.ssh/authorized_keys"
	  config.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false

		config.vm.provision "ansible" do |ansible|
			ansible.playbook = "#{vagrant_root}/test.yml"
		end

end
