---
- name: Restart Eco
  service:
    name: eco.service
    state: restarted
  ignore_errors: "{{ ansible_check_mode }}"

- name: Reload Nginx
  service:
    name: nginx.service
    state: reloaded
  ignore_errors: "{{ ansible_check_mode }}"
